### ISSUE TITLE
Local quality control report 

### ISSUE THREAD

**Issue by nhuhoa** [molonc/merFISH_report_pipeline#3]
Hi Shahid, 

I see you include azure download, and process data into your Snakemake pipeline. But this process may need permission, and some configurations. Due to many reasons, this process can be broken and affect the entire pipeline. 
Can you help to separate the whole pipeline into 2 parts: (i) connecting to azure and downloading data (ii) extracting QC reports.
 
Thanks,

**Comment by shahidhaider** [comment]
No. There is a flag to turn off direct downloading. the `is_Remote` flag satisfies this. If you set this to `No` then it will not try to download from azure and look for your data on the local filesystem. 

It is explained in the README. I did just add a line mentioning that you will need to log in to the az CLI if you choose to use this option.
